### ISSUE TITLE
sending error

### ISSUE THREAD

**Issue by goodforever** [toorop/tmail#12]
1.localhost server (installed tmail) mail.domain.com user@domain.com
2.remote client PC ,PC1 
3.on localhost server
  telnet mail.domain.com  25  
  send mail from user@domain.com to  remoteuser@other.com   OK
  send mail from user@domain.com to  user@domain.com   OK
4. on PC1
  telnet mail.domain.com 25 
  send mail from user@domain.com to  user@domain.com   OK
  send mail from user@domain.com to  remoteuser@other.com   error 554 5.7.1 Relay access denied
What do I setup mail.cfg or use tmail command to confirm this issue ?

**Comment by ro78** [comment]
If you want to allow PC1 to use tmail as a relay (without authentification), you need to use the following command:
`tmail relayip add X.X.X.X`

If you want to send emails from PC1 through tmail, you need to setup PC1 to use an account already created on tmail (auth with login/password).

**Comment by goodforever** [comment]
At first I  use an account already created on tmail (auth with login/password). then I got issue #11

**Comment by ro78** [comment]
I'm 99% sure that it's a client configuration issue on PC1. Sending emails to another host works by default.
Are you sure mail.domain.com is resolved with good IP address on PC1, and that tmail is really the program that is answering (and not Postfix or any other program) ?

Can you copy/paste tmail logs here?

**Comment by goodforever** [comment]
[iZ23x3b5pgjZ] 2016/09/08 23:03:16.049513 INFO - smtpd  e112171b9c93d7b5dd46296e402b9be39f208ac1 - 183.158.60.79:57086 - starting new transaction 1/20
[iZ23x3b5pgjZ] 2016/09/08 23:03:16.078567 ERROR - smtpd  e112171b9c93d7b5dd46296e402b9be39f208ac1 - 183.158.60.79:57086 - 454 - TLS handshake failed: remote error: bad certificate
[iZ23x3b5pgjZ] 2016/09/08 23:03:16.078846 INFO - smtpd  e112171b9c93d7b5dd46296e402b9be39f208ac1 - 183.158.60.79:57086 - EOT

**Comment by ro78** [comment]
This is about issue #11, not about relay access denied.

**Comment by goodforever** [comment]
[iZ23x3b5pgjZ] 2016/09/08 22:17:46.534555 INFO - deliverd launched
[iZ23x3b5pgjZ] 2016/09/08 22:17:52.670261 INFO - smtpd  d148ce9806b32d14a48a9ae63bf40f43b919c4b1 - 183.158.60.79:54562 - starting new transaction 1/20
[iZ23x3b5pgjZ] 2016/09/08 22:18:18.920200 INFO - smtpd  d148ce9806b32d14a48a9ae63bf40f43b919c4b1 - 183.158.60.79:54562 - MAIL FROM mag@mag.com
[iZ23x3b5pgjZ] 2016/09/08 22:18:33.109140 INFO - smtpd  d148ce9806b32d14a48a9ae63bf40f43b919c4b1 - 183.158.60.79:54562 - Relay access denied - from mag@mag.com to 24665@qdomain.com
[iZ23x3b5pgjZ] 2016/09/08 22:19:33.109412 INFO - smtpd  d148ce9806b32d14a48a9ae63bf40f43b919c4b1 - 183.158.60.79:54562 - client timeout
[iZ23x3b5pgjZ] 2016/09/08 22:19:33.109511 INFO - smtpd  d148ce9806b32d14a48a9ae63bf40f43b919c4b1 - 183.158.60.79:54562 - EOT

**Comment by ro78** [comment]
Can you give output of
`tmail rcpthost list`

**Comment by goodforever** [comment]
./tmail rcpthost list
1 magole.comremote
why add remote at end of com ?

**Comment by ro78** [comment]
It means tmail will only send emails of magole.com domain, and will not handle mailboxes locally. Not related to your issue.
Based on your logs, you have not enabled AUTH on your client.

When enabled, I see an AUTH line:

> [sd-52473] 2016/09/08 17:10:59.726874 INFO - smtpd  334d295953412956c41fa79639e9f2cff0aab561 - 127.0.0.1:33068 - starting new transaction 1/20
> [sd-52473] 2016/09/08 17:10:59.737000 INFO - smtpd  334d295953412956c41fa79639e9f2cff0aab561 - 127.0.0.1:33068 - connection upgraded to TLS 1.0 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
> [sd-52473] 2016/09/08 17:10:59.857196 INFO - smtpd  334d295953412956c41fa79639e9f2cff0aab561 - 127.0.0.1:33068 - auth succeed for user romain@mydomain.com

**Comment by goodforever** [comment]
this Relay refused logs , I use telnet mail.domain.com 25  ,not my client with account and passed.

**Comment by ro78** [comment]
If you don't see the "AUTH" line, it's normal that tmail reject the transaction because you can't send emails without being authentificated. If you are sure about client configuration, you can try
`tmail rcpthost del yourdomain.com`
`tmail rcpthost add -l yourdomain.com`
but if you client is still badly configurated, will not work

**Comment by goodforever** [comment]
Thanks ,I check my client config and test it on tomorrow , too late now

**Comment by goodforever** [comment]
My client can send email via postfix + sasl , doesn't support  TLS .
How do I config tmail for my client ?
I closed 465 port of tmail ,only launch 
[iZ23x3b5pgjZ] 2016/09/09 08:54:32.286577 INFO - smtpd 212.51.73.12:25 launched.
[iZ23x3b5pgjZ] 2016/09/09 08:54:32.292394 INFO - deliverd launched
Then  still cannot  send mail

**Comment by ro78** [comment]
Please again, post full log with error message. Even without TLS, you need to enable AUTH on client side to be able to send emails.

**Comment by goodforever** [comment]
1.   enable tmail SSL
   
   1.1  export TMAIL_SMTPD_DSNS="220.27.51.132:25:false;220.27.51.132:465:true"
   
   1.2 tmail logs
   
   ```
    tmail@iZ23x3b5pgjZ:~/dist$ sudo ./run 
    [iZ23x3b5pgjZ] 2016/09/09 21:11:13.399937 INFO - smtpd 220.27.51.132:25 launched.
    [iZ23x3b5pgjZ] 2016/09/09 21:11:13.400163 INFO - smtpd 220.27.51.132:465 SSL launched.
    [iZ23x3b5pgjZ] 2016/09/09 21:11:13.403656 INFO - deliverd launched
    [iZ23x3b5pgjZ] 2016/09/09 21:13:04.243302 INFO - smtpd 5a51fc73c8e47e0e6b1ce4583f9dfffd24980e8f - 125.118.16.220:52988 - starting new transaction 1/20
   [iZ23x3b5pgjZ] 2016/09/09 21:13:04.339881 ERROR - smtpd  5a51fc73c8e47e0e6b1ce4583f9dfffd24980e8f - 125.118.16.220:52988 - 454 - TLS handshake  failed: remote error: bad certificate
   ```
   
      [iZ23x3b5pgjZ] 2016/09/09 21:13:04.340134 INFO - smtpd  5a51fc73c8e47e0e6b1ce4583f9dfffd24980e8f - 125.118.16.220:52988 - EOT
   
   1.3 client config 
   
   ```
   host:  mail.mydomaim.com
   ```
   
      port:  25
      user:  user@mydomain.com
      passwd: userpasswd
      client logs (both of self signed and  let's encrypt ca)
      x509: certificate signed by unknown authority
2. disable SSL of tmail
   
   2.1 export TMAIL_SMTPD_DSNS="220.27.51.132:25:false
   
   2.2 tmail logs
   
   ```
   tmail@iZ23x3b5pgjZ:~/dist$ sudo ./run 
   [iZ23x3b5pgjZ] 2016/09/09 21:23:43.333701 INFO - smtpd 220.27.51.132:25 launched.
   [iZ23x3b5pgjZ] 2016/09/09 21:23:43.337880 INFO - deliverd launched
   [iZ23x3b5pgjZ] 2016/09/09 21:24:20.941927 INFO - smtpd  8319b0651b44ea4baf4f0a6ac1eabc15643a1fd7 - 125.118.16.220:53168 - starting new transaction 1/20
   [iZ23x3b5pgjZ] 2016/09/09 21:24:20.988999 ERROR - smtpd  8319b0651b44ea4baf4f0a6ac1eabc15643a1fd7 - 125.118.16.220:53168 - 454 - TLS handshake failed: remote error: bad certificate
   [iZ23x3b5pgjZ] 2016/09/09 21:24:20.989197 INFO - smtpd  8319b0651b44ea4baf4f0a6ac1eabc15643a1fd7 - 125.118.16.220:53168 - EOT
   ```
   
   2.3 client config 
   
   ```
   host:  mail.mydomaim.com
   port:  25
   user:  user@mydomain.com
   passwd: userpasswd
   ```
   
   2.4 client logs (both of self signed and  let's encrypt ca)
   
   ```
   x509: certificate signed by unknown authority
   ```

**Comment by goodforever** [comment]
I use another email client(mac OS X email client with TLS support) to test successfully
The config is 
export TMAIL_SMTPD_DSNS="220.27.51.132:25:false;220.27.51.132:465:true"

**Comment by ro78** [comment]
This is clearly not a problem on tmail side. I suggest you contacting the developer of the program you are trying to use. If certificate is configured like explained in #11, it works in Outlook, Thunderbird and Roundcube webmail.

**Comment by goodforever** [comment]
Can you recommend a client (golang) that can send mail without TLS via tmail  ?  Thanks for your tmail and your help.

**Comment by ro78** [comment]
tmail works without TLS.

**Comment by toorop** [comment]
Your client doesn't accept "untrusted" certificate (as all good client)
2 solutions:
- import the certificat in your client (with thunderbird you just have to click a button on the alert box (import or trust, i don't remember)
- sign your cert with trusted authority
