### ISSUE TITLE
Can you open the Dockerfile of  toorop/tmail  

### ISSUE THREAD

**Issue by goodforever** [toorop/tmail#13]
hi toorop,
  Can you open the Dockerfile of  toorop/tmail  ?

**Comment by toorop** [comment]
The Docker image needs update, it's based on an old version of tmail...
That said tmail is easy to install, just download the "dist.zip" archive, configure it and run it: https://github.com/toorop/tmail#quick-install-on-linux-ubuntu

**Comment by goodforever** [comment]
How do you to init sqlite auto input y in Dockerfile when RUN ./run ?
I want to know how  you write Dockerfile., so I do need your Dockerfile.

tmail@dev:~/dist$ ./run 
Database 'driver: sqlite3, source: /home/tmail/dist/db/tmail.db' misses some tables.
Should i create them ? (y/n): y

**Comment by toorop** [comment]
At the question: 
Should i create them ? (y/n): y
Just press enter to create missing table.

**Comment by goodforever** [comment]
How do you create tmail.db when you  build image of  toorop/tmail via Dockerfile ?
Because we cannot press  any key at that time.

**Comment by toorop** [comment]
I don't know and it's not really on the scope of tmail. Ask the question to the docker community.

**Comment by goodforever** [comment]
Sorry , 
Would you give me the Dockerfile of toorop/tmail ?

**Comment by toorop** [comment]
You ask the same question at the beginning of this thread... OMG we are in a infinite loop, Alert, Alert...
Seriously: no i can't give it to you because i do not have a Dockerfile for tmail.

**Comment by goodforever** [comment]
Sorry, I thought you have created this image https://hub.docker.com/r/toorop/tmail/

**Comment by toorop** [comment]
I have but not with Dokerfile.

**Comment by goodforever** [comment]
Can you tell me how you build this image ?

**Comment by toorop** [comment]
boot on an ubuntu image and follow https://github.com/toorop/tmail#quick-install-on-linux-ubuntu
